---
title: "Extracting_Alternative_Hits"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## On command line, to reduce down to 6 columns

```{bash, eval = F}
<!-- for i in $(ls *.tsv.gz) -->
<!-- do -->
<!--   zcat ${i} |\ -->
<!--     sed 's/MD.*XA:Z://' |\ -->
<!--     awk '{print $5"\t"$6}' |\ -->
<!--     sed 's/NM:i://' |\ -->
<!--     sed 's/;$//' |\ -->
<!--     tr ";" "\t" |\ -->
<!--     sed -r "s/\t([^,]*),([^,]*),([^,]*),([^,\t]*)/\t\1\t\2\t\4/g" |\ -->
<!--     gzip > 2_Filtered_${i} -->
<!-- done -->
```

```{r}
# # Load File
# alts <- read_tsv("Alternate_Hits/2_Filtered_Boleracea_Alternates.tsv.gz",
#                  col_names = c("P_NM",
#                                "Chrom_1", "Pos_1", "NM_1",
#                                "Chrom_2", "Pos_2", "NM_2",
#                                "Chrom_3", "Pos_3", "NM_3",
#                                "Chrom_4", "Pos_4", "NM_4",
#                                "Chrom_5", "Pos_5", "NM_5")
#                  )
# gc()
# head(alts)
```



```{r}
alts <- read_tsv("Alternate_Hits/Filtered_Boleracea_Alternates.tsv.gz",
                 col_names = c("P_NM","Alts"))
```


```{r}
for(i in 1:5) {
alts <- alts %>% separate(Alts, c(paste0("Hit_", i), "Alts"),
                          sep = ";",
                          fill = "right",
                          remove = TRUE,
                          extra = "merge")
}
gc()
alts$Alts <- NULL
head(alts)
gc()
```

```{r}
for(i in 1:5){
new_col <- paste0("NM_", i)
hit_col <- paste0("Hit_", i)
alts <- alts %>% mutate(!!new_col := as.numeric(str_remove(get(hit_col), ".*,")),
                        !!hit_col := ifelse(get(new_col) <= P_NM, get(hit_col), NA),
                        !!new_col := ifelse(get(new_col) <= P_NM, get(new_col), NA))
}
gc()
```

```{r}
alts <- alts %>% select(starts_with("Hit"))
alts <- alts %>% pivot_longer(cols = 1:5,
                              names_to = "Hit",
                              values_to = "Mapping",
                              values_drop_na = TRUE) %>%
                 separate(col = Mapping,
                          into = c("Chromosome", "Position", "CIGAR", "NM"),
                          convert = TRUE) %>%
                 mutate(Position = abs(Position)) %>%
                 select(Chromosome, Position) %>%
                 arrange(Chromosome, Position)
gc()
head(alts)
```
###

## Chunk loading
```{r}
Hit_Processor <- function(x, pos) {
  for (i in 1:5) {
    x <- x %>% separate(
      Alts,
      c(paste0("Hit_", i), "Alts"),
      sep = ";",
      fill = "right",
      remove = TRUE,
      extra = "merge"
    )
  }
  for (i in 1:5) {
    new_col <- paste0("NM_", i)
    hit_col <- paste0("Hit_", i)
    x <-
      x %>% mutate(
        !!new_col := as.numeric(str_remove(get(hit_col), ".*,")),!!hit_col := ifelse(get(new_col) <= P_NM, get(hit_col), NA),!!new_col := ifelse(get(new_col) <= P_NM, get(new_col), NA)
      )
  }
  x <- x %>% select(starts_with("Hit"))
  x <- x %>% pivot_longer(
    cols = 1:5,
    names_to = "Hit",
    values_to = "Mapping",
    values_drop_na = TRUE
  ) %>%
    separate(
      col = Mapping,
      into = c("Chromosome", "Position", "CIGAR", "NM"),
      convert = TRUE
    ) %>%
    mutate(Position = abs(Position)) %>%
    select(Chromosome, Position) %>%
    arrange(Chromosome, Position)
}
alts <- read_tsv_chunked("Alternate_Hits/Filtered_Boleracea_Alternates.tsv.gz", 
                DataFrameCallback$new(Hit_Processor),
                col_names = c("P_NM","Alts"),
                progress = TRUE,
                chunk_size = 10000)
write_tsv(alts, "Boleracea_Alternates_sites.tsv.gz")
```

## Run on the rest

```{r}
Assemblies <- (list.files("Alternate_Hits", pattern = "^Filtered") %>%
  str_remove(., "Filtered_") %>%
  str_remove(., "_Alternates.tsv.gz"))[-1]

for(i in Assemblies) {
  alts <-
    read_tsv_chunked(
      paste0("Alternate_Hits/Filtered_", i, "_Alternates.tsv.gz"),
      DataFrameCallback$new(Hit_Processor),
      col_names = c("P_NM", "Alts"),
      progress = TRUE,
      chunk_size = 10000
    )
  write_tsv(alts,
            paste0("Alternate_Hits/", i, "_Alternates_sites.tsv.gz"))
  rm(alts)
  gc()
}
```

