---
title: "Sequence_Level_Homology"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
## Read in the calculated coverages
coverage_columns <- c("Chromosome", "Start", "End", "Reads", "Covered", "Size", "Ratio")
Coverage_Readin <- function(filename){
  df <- read_delim(filename,
                   col_names = coverage_columns,
                   delim = "\t",
                   skip = 2) %>%
    mutate(Adjusted_Coverage = round(Reads / Size, 2),
           Position = floor((End + Start) / 2)) %>%
    group_by(Chromosome) %>%
    mutate(Chromosome_Average = mean(Adjusted_Coverage, na.rm = T),
           Chromosome_SD = sd(Adjusted_Coverage, na.rm = T),
           Relative_Coverage = round(Adjusted_Coverage / Chromosome_Average, 2),
           Relative_Coverage = ifelse(Relative_Coverage >= 10, NA, Relative_Coverage),
           Std_Relative_Coverage = scale(Relative_Coverage)) %>%
    ungroup()
  return(df)
}

Pseudo_napus_Coverage <- Coverage_Readin("Combined_Coverages/Combined_pseudo_napus_Coverage.tsv.gz")
DaAe_Coverage <- Coverage_Readin("Combined_Coverages/Combined_DaAe_Coverage.tsv.gz")
```

# Format the data a bit

```{r}
Pseudo_napus_Coverage <- Pseudo_napus_Coverage %>%
  mutate(Assembly = "Pseudo_napus",
         Chromosome = ifelse(grepl("C", Chromosome),
                             str_replace(Chromosome, "C", "chrC0"),
                             paste0("chr",Chromosome))
  )
DaAe_Coverage$Assembly <- "DaAe"
```

## Clustering a bit

```{r}
# Set the value of each point equal to most frequent rounded value in 20 neighbors will have to burn in 10
Clustered_Pseudo_napus_Coverage <- Pseudo_napus_Coverage %>%
  mutate(Consensus = NA)

for(i in 11:(nrow(Clustered_Pseudo_napus_Coverage)-10)){
  Neighbors <- round(Clustered_Pseudo_napus_Coverage$Std_Relative_Coverage[(i-10):(i+10)],1)
  #winner <- as.numeric(names(table(neighbors))[table(neighbors)==max(table(neighbors))])
  Winner <- median(Neighbors, na.rm = T)
  if(is_empty(Winner)) Winner <- Clustered_Pseudo_napus_Coverage$Consensus[i-1]
  Clustered_Pseudo_napus_Coverage$Consensus[i] <- round(mean(Winner),1)
}

# Factor in Napus

Clustered_DaAe_Coverage <- DaAe_Coverage %>%
  mutate(Consensus = NA)

for(i in 11:(nrow(Clustered_DaAe_Coverage)-10)){
  Neighbors <- round(Clustered_DaAe_Coverage$Std_Relative_Coverage[(i-10):(i+10)],1)
  #winner <- as.numeric(names(table(neighbors))[table(neighbors)==max(table(neighbors))])
  Winner <- median(Neighbors, na.rm = T)
  if(is_empty(Winner)) Winner <- Clustered_DaAe_Coverage$Consensus[i-1]
  Clustered_DaAe_Coverage$Consensus[i] <- round(mean(Winner),1)
}

Clustered_All <- rbind(Clustered_Pseudo_napus_Coverage, Clustered_DaAe_Coverage)
Clustered_All$Assembly <- factor(Clustered_All$Assembly, levels = c("Pseudo_napus", "DaAe"))
```

### Plots

```{r}
chroms <- c(paste0("chrA0",1:9), "chrA10", paste0("chrC0", 1:9))
for (i in chroms) {
  Clustered_All %>% filter(Chromosome == i) %>%
    mutate(Consensus = ifelse(Consensus >= 4,
                                          4,
                                          ifelse(Consensus <= -4,
                                                 -4,
                                                 Consensus))) %>%
    ggplot(aes(x = Position, y = Consensus)) +
    geom_point(aes(colour = cut(Consensus, c(-Inf, -1, 1, Inf)))) +
    scale_color_manual(name = "Consensus",
                     values = c("(-Inf,-1]" = "red",
                                  "(-1,1]" = "black",
                                  "(1, Inf]" = "blue"),
                     labels = c("<= -1", "-1 < Consensus <= 1", "> 1")) +
    ggtitle(i) +
    geom_hline(yintercept = 1, color="black") +
    geom_hline(yintercept = 0, color="black") +
    geom_hline(yintercept = -1, color="black") +
    facet_wrap(~Assembly,
               ncol = 2,
               labeller = function (labels) {
                 labels <- lapply(labels, as.character)
                 labels[[1]] <- paste("Assembly:", labels[[1]])
                 a <-  do.call(paste,c(labels, list(sep = "\n")))
                 list(gsub("_","",a))
                 })
  ggsave(paste0("Coverage_Plots_20220701/",i,".png"))
}
```

#######
#######
# Add in more napus genomes

```{r}
library(tidyverse)
```

```{r}
## Read in the calculated coverages
coverage_columns <- c("Chromosome", "Start", "End", "Reads", "Covered", "Size", "Ratio")
Coverage_Readin <- function(filename){
  df <- read_delim(filename,
                   col_names = coverage_columns,
                   delim = "\t",
                   skip = 2) %>%
    mutate(Adjusted_Coverage = round(Reads / Size, 2),
           Position = floor((End + Start) / 2)) %>%
    group_by(Chromosome) %>%
    mutate(Chromosome_Average = mean(Adjusted_Coverage, na.rm = T),
           Chromosome_SD = sd(Adjusted_Coverage, na.rm = T),
           Relative_Coverage = round(Adjusted_Coverage / Chromosome_Average, 2),
           Relative_Coverage = ifelse(Relative_Coverage >= 10, NA, Relative_Coverage),
           Std_Relative_Coverage = scale(Relative_Coverage)) %>%
    ungroup()
  return(df)
}

Pseudo_napus_Coverage <- Coverage_Readin("Combined_Coverages/Combined_pseudo_napus_Coverage.tsv.gz")
DaAe_Coverage <- Coverage_Readin("Combined_Coverages/Combined_DaAe_Coverage.tsv.gz")
ZS11_Coverage <- Coverage_Readin("Combined_Coverages/Combined_ZS11_Coverage.tsv.gz")
Darmor_Bzh_V10_Coverage <- Coverage_Readin("Combined_Coverages/Combined_Darmor-Bzh_V10_Coverage.tsv.gz")
```

# Format the data a bit

```{r}
Pseudo_napus_Coverage <- Pseudo_napus_Coverage %>%
  mutate(Assembly = "Pseudo_napus",
         Chromosome = ifelse(grepl("C", Chromosome),
                             str_replace(Chromosome, "C", "chrC0"),
                             paste0("chr",Chromosome))
  )
DaAe_Coverage$Assembly <- "DaAe"
ZS11_Coverage <- ZS11_Coverage %>%
  mutate(Assembly = "ZS11",
         Chromosome = str_replace(Chromosome, "scaffold", "chr"))
Darmor_Bzh_V10_Coverage <- Darmor_Bzh_V10_Coverage %>%
  mutate(Assembly = "Darmor-Bzh_V10",
         Chromosome = str_c("chr", Chromosome))
All_Coverage <- rbind(Pseudo_napus_Coverage, DaAe_Coverage, ZS11_Coverage, Darmor_Bzh_V10_Coverage)
```


## Clustering a bit

```{r}
# Set the value of each point equal to most frequent rounded value in 20 neighbors will have to burn in 10
Clustered_Pseudo_napus_Coverage <- Pseudo_napus_Coverage %>%
  mutate(Consensus = NA)

for(i in 11:(nrow(Clustered_Pseudo_napus_Coverage)-10)){
  Neighbors <- round(Clustered_Pseudo_napus_Coverage$Std_Relative_Coverage[(i-10):(i+10)],1)
  #winner <- as.numeric(names(table(neighbors))[table(neighbors)==max(table(neighbors))])
  Winner <- median(Neighbors, na.rm = T)
  if(is_empty(Winner)) Winner <- Clustered_Pseudo_napus_Coverage$Consensus[i-1]
  Clustered_Pseudo_napus_Coverage$Consensus[i] <- round(mean(Winner),1)
}

# Factor in Napus

Clustered_DaAe_Coverage <- DaAe_Coverage %>%
  mutate(Consensus = NA)

Clustered_ZS11_Coverage <- ZS11_Coverage %>%
  mutate(Consensus = NA)

Clustered_Darmor_Bzh_V10_Coverage <- Darmor_Bzh_V10_Coverage %>%
  mutate(Consensus = NA)

for(i in 11:(nrow(Clustered_DaAe_Coverage)-10)){
  Neighbors <- round(Clustered_DaAe_Coverage$Std_Relative_Coverage[(i-10):(i+10)],1)
  #winner <- as.numeric(names(table(neighbors))[table(neighbors)==max(table(neighbors))])
  Winner <- median(Neighbors, na.rm = T)
  if(is_empty(Winner)) Winner <- Clustered_DaAe_Coverage$Consensus[i-1]
  Clustered_DaAe_Coverage$Consensus[i] <- round(mean(Winner),1)
}

for(i in 11:(nrow(Clustered_ZS11_Coverage)-10)){
  Neighbors <- round(Clustered_ZS11_Coverage$Std_Relative_Coverage[(i-10):(i+10)],1)
  #winner <- as.numeric(names(table(neighbors))[table(neighbors)==max(table(neighbors))])
  Winner <- median(Neighbors, na.rm = T)
  if(is_empty(Winner)) Winner <- Clustered_ZS11_Coverage$Consensus[i-1]
  Clustered_ZS11_Coverage$Consensus[i] <- round(mean(Winner),1)
}

for(i in 11:(nrow(Clustered_Darmor_Bzh_V10_Coverage)-10)){
  Neighbors <- round(Clustered_Darmor_Bzh_V10_Coverage$Std_Relative_Coverage[(i-10):(i+10)],1)
  #winner <- as.numeric(names(table(neighbors))[table(neighbors)==max(table(neighbors))])
  Winner <- median(Neighbors, na.rm = T)
  if(is_empty(Winner)) Winner <- Clustered_Darmor_Bzh_V10_Coverage$Consensus[i-1]
  Clustered_Darmor_Bzh_V10_Coverage$Consensus[i] <- round(mean(Winner),1)
}

Clustered_All <- rbind(Clustered_Pseudo_napus_Coverage, Clustered_DaAe_Coverage, Clustered_ZS11_Coverage, Clustered_Darmor_Bzh_V10_Coverage)
Clustered_All$Assembly <- factor(Clustered_All$Assembly, levels = c("Pseudo_napus", "DaAe", "ZS11", "Darmor-Bzh_V10"))
```

# Load Position data
```{r}
load("DaAe_Gene_Positions.RData")
load("ZS11_Gene_Positions.RData")
load("Darmor-Bzh_V10_Gene_Positions.RData")

name_fix <- function(positions, assembly_name = "", doubled = "A"){
  df <- positions %>%
    mutate(Chromosome = sub("chr", "", Chromosome),
           Chromosome = sub("scaffold", "", Chromosome),
           Chromosome = ifelse(Assembly == "Pseudo_napus",
                               str_replace(Chromosome,"C", "C0"),
                               Chromosome),
           Chromosome = paste0("chr",Chromosome),
           Y = ifelse(grepl(doubled,Chromosome), 3.5, -3.5),
           Shaped = ifelse(Y == 3.5, "<", ">"),
           Assembly = ifelse(Assembly == "Napus", assembly_name, Assembly)) %>%
    select(Chromosome, Position, Y, Assembly, Shaped)
  return(df)
}

DA_DaAe_Positions <- name_fix(DA_DaAe_Positions, "DaAe", "A")
DA_ZS11_Positions <- name_fix(DA_ZS11_Positions, "ZS11", "A")
DA_Darmor_Bzh_V10_Positions <- name_fix(DA_Darmor_Bzh_V10_Positions, "Darmor-Bzh_V10", "A")
DC_DaAe_Positions <- name_fix(DC_DaAe_Positions, "DaAe", "C")
DC_ZS11_Positions <- name_fix(DC_ZS11_Positions, "ZS11", "C")
DC_Darmor_Bzh_V10_Positions <- name_fix(DC_Darmor_Bzh_V10_Positions, "Darmor-Bzh_V10", "C")

All_Positions <- rbind(DA_DaAe_Positions, DA_ZS11_Positions, DA_Darmor_Bzh_V10_Positions,
                       DC_DaAe_Positions, DC_ZS11_Positions, DC_Darmor_Bzh_V10_Positions)
```

# Plot

```{r}
chroms <- c(paste0("chrA0",1:9), "chrA10", paste0("chrC0", 1:9))
for (i in chroms) {
  Clustered_All %>% filter(Chromosome == i) %>%
    mutate(Consensus = ifelse(Consensus >= 4,
                                          4,
                                          ifelse(Consensus <= -4,
                                                 -4,
                                                 Consensus))) %>%
    ggplot(aes(x = Position, y = Consensus)) +
    geom_point(aes(colour = cut(Consensus, c(-Inf, -1, 1, Inf)))) +
    scale_color_manual(name = "Consensus",
                     values = c("(-Inf,-1]" = "red",
                                  "(-1,1]" = "black",
                                  "(1, Inf]" = "blue"),
                     labels = c("<= -1", "-1 < Consensus <= 1", "> 1")) +
    ggtitle(i) +
    geom_hline(yintercept = 1, color="black") +
    geom_hline(yintercept = 0, color="black") +
    geom_hline(yintercept = -1, color="black") +
    facet_wrap(~Assembly,
               ncol = 2,
               labeller = function (labels) {
                 labels <- lapply(labels, as.character)
                 labels[[1]] <- paste("Assembly:", labels[[1]])
                 a <-  do.call(paste,c(labels, list(sep = "\n")))
                 list(gsub("_","",a))
                 }) +
    geom_text(data = All_Positions %>% filter(Chromosome == i),
               aes(x = Position, y = Y, label = Shaped))
  ggsave(paste0("Coverage_Plots_20220701/",i,".png"), width = 10, height = 10)
}

save(Clustered_All, All_Positions, file = "Coverages_and_Positions.RData")
```

################
# Explore areas where gene and sequence level HE overlap

```{r}
library(tidyverse)
load("Coverages_and_Positions.RData")
chroms <- c(paste0("chrA0",1:9), "chrA10", paste0("chrC0", 1:9))
for (i in chroms) {
  Clustered_All %>% filter(Chromosome == i) %>%
    mutate(Consensus = ifelse(Consensus >= 4,
                                          4,
                                          ifelse(Consensus <= -4,
                                                 -4,
                                                 Consensus))) %>%
    ggplot(aes(x = Position, y = Consensus)) +
    geom_point(aes(colour = cut(Consensus, c(-Inf, -1, 1, Inf)))) +
    scale_color_manual(name = "Consensus",
                     values = c("(-Inf,-1]" = "red",
                                  "(-1,1]" = "black",
                                  "(1, Inf]" = "blue"),
                     labels = c("<= -1", "-1 < Consensus <= 1", "> 1")) +
    ggtitle(i) +
    geom_hline(yintercept = 1, color="black") +
    geom_hline(yintercept = 0, color="black") +
    geom_hline(yintercept = -1, color="black") +
    facet_wrap(~Assembly,
               ncol = 2,
               labeller = function (labels) {
                 labels <- lapply(labels, as.character)
                 labels[[1]] <- paste("Assembly:", labels[[1]])
                 a <-  do.call(paste,c(labels, list(sep = "\n")))
                 list(gsub("_","",a))
                 }) #+
    #geom_text(data = All_Positions %>% filter(Chromosome == i),
               #aes(x = Position, y = Y, label = Shaped))
  ggsave(paste0("Coverage_Plots_20220817/",i,".png"), width = 10, height = 10)
}

```

# Get weird with it
```{r}
chroms <- c(paste0("chrA0", 1:9), "chrA10", paste0("chrC0", 1:9))
for (i in chroms) {
  Clustered_All %>% filter(Chromosome == i) %>%
    mutate(Consensus = ifelse(Consensus >= 4,
                              4,
                              ifelse(Consensus <= -4,-4,
                                     Consensus))) %>%
    ggplot(aes(x = Position, y = Consensus)) +
    geom_point(aes(colour = Assembly)) +
    ggtitle(i) +
    geom_hline(yintercept = 1, color = "black") +
    geom_hline(yintercept = 0, color = "black") +
    geom_hline(yintercept = -1, color = "black") +
    geom_text(
      data = All_Positions %>% filter(Chromosome == i),
      aes(
        x = Position,
        y = Y,
        label = Shaped,
        color = Assembly
      )
    )
  ggsave(
    paste0("Combined_Coverage_Plots_20220817/", i, ".png"),
    width = 10,
    height = 10
  )
}
```

```{r}
# Want regions greater than 1 std deviation in coverage
Filtered_Clustered_All<- Clustered_All #%>%
  #filter(Consensus <= -1 | Consensus >= 1)

# Want overlap of genes and sequence regions
DaAe_Seq <- Filtered_Clustered_All %>%
  filter(Assembly == "DaAe")
DaAe_Gene <- All_Positions %>%
  filter(Assembly == "DaAe")

Filtered_DaAe_Gene <- data.frame(matrix(ncol = ncol(DaAe_Gene), nrow = 0))
colnames(Filtered_DaAe_Gene) <- colnames(DaAe_Gene)
Filtered_DaAe_Seq <- data.frame(matrix(ncol = ncol(DaAe_Seq), nrow = 0))
colnames(Filtered_DaAe_Seq) <- colnames(DaAe_Seq)

# Get the genes in the regions
for(i in 1:nrow(DaAe_Gene)){
  chrom <- DaAe_Gene[[i,1]]
  pos <- DaAe_Gene[[i,2]]
  temp <- DaAe_Seq %>% filter(Chromosome == chrom)
  if(nrow(temp) == 0) next
  for(j in 1:nrow(temp)){
    if(temp[[j,2]] <= pos & temp[[j,3]] >= pos){
      Filtered_DaAe_Gene <- rbind(Filtered_DaAe_Gene, DaAe_Gene[i,])
      break
    }
  }
}

# Get the regions the genes are in
for(i in 1:nrow(DaAe_Seq)){
  chrom <- DaAe_Seq[[i,1]]
  start <- DaAe_Seq[[i,2]]
  end <- DaAe_Seq[[i,3]]
  temp <- Filtered_DaAe_Gene %>% filter(Chromosome == chrom)
  if(nrow(temp) == 0) next
  for(j in 1:nrow(temp)){
    if(temp[[j,2]] >= start & temp[[j,2]] <= end){
      Filtered_DaAe_Seq <- rbind(Filtered_DaAe_Seq, DaAe_Seq[i,])
      break
    }
  }
}

# Repeat for the other 3. This could be done a whole lot cleaner
# Want overlap of genes and sequence regions
ZS11_Seq <- Filtered_Clustered_All %>%
  filter(Assembly == "ZS11")
ZS11_Gene <- All_Positions %>%
  filter(Assembly == "ZS11")

Filtered_ZS11_Gene <- data.frame(matrix(ncol = ncol(ZS11_Gene), nrow = 0))
colnames(Filtered_ZS11_Gene) <- colnames(ZS11_Gene)
Filtered_ZS11_Seq <- data.frame(matrix(ncol = ncol(ZS11_Seq), nrow = 0))
colnames(Filtered_ZS11_Seq) <- colnames(ZS11_Seq)

# Get the genes in the regions
for(i in 1:nrow(ZS11_Gene)){
  chrom <- ZS11_Gene[[i,1]]
  pos <- ZS11_Gene[[i,2]]
  temp <- ZS11_Seq %>% filter(Chromosome == chrom)
  if(nrow(temp) == 0) next
  for(j in 1:nrow(temp)){
    if(temp[[j,2]] <= pos & temp[[j,3]] >= pos){
      Filtered_ZS11_Gene <- rbind(Filtered_ZS11_Gene, ZS11_Gene[i,])
      break
    }
  }
}

# Get the regions the genes are in
for(i in 1:nrow(ZS11_Seq)){
  chrom <- ZS11_Seq[[i,1]]
  start <- ZS11_Seq[[i,2]]
  end <- ZS11_Seq[[i,3]]
  temp <- Filtered_ZS11_Gene %>% filter(Chromosome == chrom)
  if(nrow(temp) == 0) next
  for(j in 1:nrow(temp)){
    if(temp[[j,2]] >= start & temp[[j,2]] <= end){
      Filtered_ZS11_Seq <- rbind(Filtered_ZS11_Seq, ZS11_Seq[i,])
      break
    }
  }
}

# Want overlap of genes and sequence regions
Darmor_Bzh_V10_Seq <- Filtered_Clustered_All %>%
  filter(Assembly == "Darmor-Bzh_V10")
Darmor_Bzh_V10_Gene <- All_Positions %>%
  filter(Assembly == "Darmor-Bzh_V10")

Filtered_Darmor_Bzh_V10_Gene <- data.frame(matrix(ncol = ncol(Darmor_Bzh_V10_Gene), nrow = 0))
colnames(Filtered_Darmor_Bzh_V10_Gene) <- colnames(Darmor_Bzh_V10_Gene)
Filtered_Darmor_Bzh_V10_Seq <- data.frame(matrix(ncol = ncol(Darmor_Bzh_V10_Seq), nrow = 0))
colnames(Filtered_Darmor_Bzh_V10_Seq) <- colnames(Darmor_Bzh_V10_Seq)

# Get the genes in the regions
for(i in 1:nrow(Darmor_Bzh_V10_Gene)){
  chrom <- Darmor_Bzh_V10_Gene[[i,1]]
  pos <- Darmor_Bzh_V10_Gene[[i,2]]
  temp <- Darmor_Bzh_V10_Seq %>% filter(Chromosome == chrom)
  if(nrow(temp) == 0) next
  for(j in 1:nrow(temp)){
    if(temp[[j,2]] <= pos & temp[[j,3]] >= pos){
      Filtered_Darmor_Bzh_V10_Gene <- rbind(Filtered_Darmor_Bzh_V10_Gene, Darmor_Bzh_V10_Gene[i,])
      break
    }
  }
}

# Get the regions the genes are in
for(i in 1:nrow(Darmor_Bzh_V10_Seq)){
  chrom <- Darmor_Bzh_V10_Seq[[i,1]]
  start <- Darmor_Bzh_V10_Seq[[i,2]]
  end <- Darmor_Bzh_V10_Seq[[i,3]]
  temp <- Filtered_Darmor_Bzh_V10_Gene %>% filter(Chromosome == chrom)
  if(nrow(temp) == 0) next
  for(j in 1:nrow(temp)){
    if(temp[[j,2]] >= start & temp[[j,2]] <= end){
      Filtered_Darmor_Bzh_V10_Seq <- rbind(Filtered_Darmor_Bzh_V10_Seq, Darmor_Bzh_V10_Seq[i,])
      break
    }
  }
}

# Want overlap of genes and sequence regions
Pseudo_napus_Seq <- Filtered_Clustered_All %>%
  filter(Assembly == "Pseudo_napus")
Pseudo_napus_Gene <- All_Positions %>%
  filter(Assembly == "Pseudo_napus")

Filtered_Pseudo_napus_Gene <- data.frame(matrix(ncol = ncol(Pseudo_napus_Gene), nrow = 0))
colnames(Filtered_Pseudo_napus_Gene) <- colnames(Pseudo_napus_Gene)
Filtered_Pseudo_napus_Seq <- data.frame(matrix(ncol = ncol(Pseudo_napus_Seq), nrow = 0))
colnames(Filtered_Pseudo_napus_Seq) <- colnames(Pseudo_napus_Seq)

# Get the genes in the regions
for(i in 1:nrow(Pseudo_napus_Gene)){
  chrom <- Pseudo_napus_Gene[[i,1]]
  pos <- Pseudo_napus_Gene[[i,2]]
  temp <- Pseudo_napus_Seq %>% filter(Chromosome == chrom)
  if(nrow(temp) == 0) next
  for(j in 1:nrow(temp)){
    if(temp[[j,2]] <= pos & temp[[j,3]] >= pos){
      Filtered_Pseudo_napus_Gene <- rbind(Filtered_Pseudo_napus_Gene, Pseudo_napus_Gene[i,])
      break
    }
  }
}

# Get the regions the genes are in
for(i in 1:nrow(Pseudo_napus_Seq)){
  chrom <- Pseudo_napus_Seq[[i,1]]
  start <- Pseudo_napus_Seq[[i,2]]
  end <- Pseudo_napus_Seq[[i,3]]
  temp <- Filtered_Pseudo_napus_Gene %>% filter(Chromosome == chrom)
  if(nrow(temp) == 0) next
  for(j in 1:nrow(temp)){
    if(temp[[j,2]] >= start & temp[[j,2]] <= end){
      Filtered_Pseudo_napus_Seq <- rbind(Filtered_Pseudo_napus_Seq, Pseudo_napus_Seq[i,])
      break
    }
  }
}

# Combine together
Combined_Gene <- rbind(Filtered_DaAe_Gene, Filtered_Darmor_Bzh_V10_Gene,
                       Filtered_ZS11_Gene, Filtered_Pseudo_napus_Gene)

Combined_Seq <- rbind(Filtered_DaAe_Seq, Filtered_Darmor_Bzh_V10_Seq,
                       Filtered_ZS11_Seq, Filtered_Pseudo_napus_Seq)

# Plot
chroms <- c(paste0("chrA0", 1:9), "chrA10", paste0("chrC0", 1:9))
for (i in chroms) {
  Combined_Seq %>% filter(Chromosome == i) %>%
    mutate(Consensus = ifelse(Consensus >= 4,
                              4,
                              ifelse(Consensus <= -4,-4,
                                     Consensus))) %>%
    ggplot(aes(x = Position, y = Consensus)) +
    geom_point(aes(colour = Assembly)) +
    ggtitle(i) +
    geom_hline(yintercept = 1, color = "black") +
    geom_hline(yintercept = 0, color = "black") +
    geom_hline(yintercept = -1, color = "black") +
    geom_text(
      data = Combined_Gene %>% filter(Chromosome == i),
      aes(
        x = Position,
        y = Y,
        label = Shaped,
        color = Assembly
      )
    )
  ggsave(
    paste0("Combined_Coverage_Plots_20220817/", i, ".png"),
    width = 10,
    height = 10
  )
}
```

